version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: ["alembic", "upgrade", "head"]
    depends_on:
      - db

volumes:
  postgres_data:
