"""update Invitation/User relatioship

Revision ID: 603c872a339f
Revises: a040b7368253
Create Date: 2023-11-08 15:32:36.261061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603c872a339f'
down_revision = 'a040b7368253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitation', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitation', type_='unique')
    # ### end Alembic commands ###
