"""Course Rating Updates

Revision ID: 2cdf6c3dd0f1
Revises: 641446871ae9
Create Date: 2024-03-06 18:11:03.737805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf6c3dd0f1'
down_revision = '641446871ae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
