"""Add course_image field

Revision ID: 2a3b8fc88d16
Revises: 7bcca41d3d9d
Create Date: 2024-03-27 14:20:34.623812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3b8fc88d16'
down_revision = '7bcca41d3d9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'course_image')
    # ### end Alembic commands ###
